services:
    sqlserverdb:
        container_name: sqlservercontainer
        image: mcr.microsoft.com/mssql/server:2022-latest
        volumes:
            - C:/tmp/PhoneixTaskDb:/var/opt/mssql/data
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=A123456789a*
        healthcheck:
            test:  /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "A123456789a*" -C -Q "SELECT 1" || exit 1
            interval: 1s
            timeout: 20s
            retries: 100
            start_period: 10s
    webapi:
        container_name: webapicontainer
        image: $phoenixTask
        volumes:
            - C:/tmp/PhoneixTaskLogs:/app/logs
        ports:
            - 2023:8080 
            - 44388:44388
        build:
          context: .
          dockerfile: src/PhoenixTask.WebApi/Dockerfile
        environment:
            - ASPNETCORE_Kestrel__Certificates__Default__Path:'localhost-dev.pfx'
        depends_on:
            sqlserverdb:
                condition: service_healthy
